[project]
name = "s3-object-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.36",
    "pytz>=2025.2",
    "streamlit>=1.45.1",
]
